name: Tests workflow

on:
  push:

env:
  FRAMEWORK: node

jobs:
  test:
    strategy:
      fail-fast: true

    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - run: yarn install --pure-lockfile
      - name: Running Tests
        run: yarn test:ci
        id: tests
